spring.application.name=spring-la-mia-pizzeria-crud

#data source
spring.datasource.url=jdbc:mysql://localhost:3306/pizzas_db
spring.datasource.username=root
spring.datasource.password=root

# hibernate settings 
spring.jpa.hibernate.ddl-auto=update