INSERT INTO pizza (name, description, price, img) VALUES
('Margherita', 'Pomodoro, mozzarella, basilico fresco e olio EVO', 5.00, 'margherita.jpg'),
('Marinara', 'Pomodoro, aglio, origano e olio EVO', 4.00, 'marinara.jpg'),
('Diavola', 'Pomodoro, mozzarella, salame piccante e peperoncino', 7.50, 'diavola.jpg'),
('Quattro Formaggi', 'Mozzarella, gorgonzola, fontina e parmigiano', 8.50, 'quattro-formaggi.jpg'),
('Capricciosa', 'Pomodoro, mozzarella, funghi, carciofi, prosciutto cotto e olive', 9.00, 'capricciosa.jpg'),
('Napoli', 'Pomodoro, mozzarella, acciughe e origano', 7.00, 'napoli.jpg'),
('Bufalina', 'Pomodoro, mozzarella di bufala campana DOP e basilico', 8.50, 'bufalina.jpg'),
('Vegetariana', 'Pomodoro, mozzarella e verdure grigliate di stagione', 8.00, 'vegetariana.jpg'),
('Quattro Stagioni', 'Divisa in 4: funghi, carciofi, prosciutto cotto e olive', 9.00, 'quattro-stagioni.jpg'),
('Salsiccia e Friarielli', 'Mozzarella, salsiccia fresca e friarielli saltati', 9.50, 'salsiccia-friarielli.jpg'),
('Boscaiola', 'Mozzarella, funghi champignon e salsiccia', 8.50, 'boscaiola.jpg'),
('Tirolese', 'Pomodoro, mozzarella, speck e gorgonzola', 9.00, 'tirolese.jpg'),
('Tonno e Cipolla', 'Pomodoro, mozzarella, tonno e cipolla rossa di Tropea', 8.00, 'tonno-cipolla.jpg'),
('Crudo e Rucola', 'Pomodoro, mozzarella, prosciutto crudo, rucola e scaglie di grana', 10.00, 'crudo-rucola.jpg'),
('Americana', 'Pomodoro, mozzarella, wurstel e patatine fritte', 7.50, 'americana.jpg'),
('Calzone Classico', 'Pomodoro, mozzarella, prosciutto cotto e funghi (chiuso)', 8.50, 'calzone.jpg'),
('Pistacchiosa', 'Mozzarella, pesto di pistacchio, mortadella e granella di pistacchi', 11.00, 'pistacchiosa.jpg'),
('Nduja', 'Pomodoro, mozzarella, nduja calabrese e cipolla rossa', 9.00, 'nduja.jpg'),
('Schiacciata Bianca', 'Olio, sale e rosmarino', 3.50, 'schiacciata.jpg'),
('Carbonara', 'Mozzarella, uovo, guanciale e pecorino romano', 9.50, 'carbonara.jpg'),
('Messinese', 'Scarola, pomodoro a fette, acciughe e tuma o mozzarella', 8.50, 'messinese.jpg'),
('Amatriciana', 'Pomodoro, guanciale, pecorino e peperoncino', 9.00, 'amatriciana.jpg'),
('Tartufata', 'Mozzarella, crema di tartufo, funghi porcini e speck', 12.00, 'tartufata.jpg'),
('Pugliese', 'Pomodoro, mozzarella, cipolla e olive nere', 7.50, 'pugliese.jpg'),
('Bresaola e Valtellina', 'Mozzarella, bresaola, rucola e scaglie di parmigiano', 10.50, 'bresaola.jpg'),
('Zucchine e Gamberetti', 'Mozzarella, zucchine trifolate e gamberetti', 10.00, 'zucchine-gamberetti.jpg'),
('Ortolana Bianca', 'Mozzarella, spinaci, melanzane e peperoni', 8.00, 'ortolana.jpg'),
('Porcina', 'Pomodoro, mozzarella e funghi porcini freschi', 9.50, 'porcina.jpg'),
('Salame Dolce', 'Pomodoro, mozzarella e salame Milano', 7.00, 'salame-dolce.jpg'),
('Cotto e Mais', 'Pomodoro, mozzarella, prosciutto cotto e mais', 7.50, 'cotto-mais.jpg');